Repository nLatt/GLaDOS-2023, pull requests merged in 2023-03, with the labels that each got.

#93 89 create array handling
  doc/bonuses.md
  lib/Exec/Builtins.hs
  lib/Exec/Utils.hs
  lib/Parsing/Ast.hs
  lib/Parsing/Cpt.hs
  lib/Parsing/Token.hs
Labels: Feature, Bonus

#96 92 implement float operations
  doc/bonuses.md
  integrationTests/TestFiles/float_mul.scm
  integrationTests/TestFiles/float_mul.scm.slv
  lib/Exec/Builtins.hs
  lib/Exec/InteractivePrompt.hs
  lib/Exec/Utils.hs
  lib/Parsing/Ast.hs
  lib/Parsing/Cpt.hs
  lib/Parsing/Token.hs
  unitTest/ExecTests.hs
  unitTest/ke
Labels: Feature, Bonus

#97 74 implement reading from stdin
  GLaDOS2023.cabal
  app/Main.hs
  lib/Exec/Builtins.hs
  lib/Exec/Utils.hs
  lib/Parsing/Ast.hs
  lib/Parsing/Cpt.hs
  lib/Parsing/Token.hs
  lib/Parsing/TokenType.hs
  unitTest/Parsing/CptTests.hs
  unitTest/Parsing/InfixTests.hs
  unitTest/Parsing/TokenTests.hs
Labels: Feature, Bonus

#98 [Refactor] simplified isAtomic
  doc/bonuses.md
  lib/Exec/Eval.hs
  lib/Exec/InteractivePrompt.hs
  lib/Exec/Utils.hs
  lib/Parsing/Ast.hs
  lib/Parsing/Infix.hs
  lib/Parsing/Token.hs
Labels: Feature, Refacto

#102 [Feature] add infix signature for custom functions
  doc/syntax-description.md
Labels: Documentation

#99 Develop
  GLaDOS2023.cabal
  app/Main.hs
  doc/bonuses.md
  doc/syntax-description.md
  lib/Exec/Builtins.hs
  lib/Exec/Eval.hs
  lib/Exec/InteractivePrompt.hs
  lib/Exec/Utils.hs
  lib/Parsing/Ast.hs
  lib/Parsing/Cpt.hs
  lib/Parsing/Infix.hs
  lib/Parsing/Token.hs
  lib/Parsing/TokenType.hs
  unitTest/Parsing/CptTests.hs
  unitTest/Parsing/InfixTests.hs
  unitTest/Parsing/TokenTests.hs
Labels: Release

#108 [Doc] add compiled syntax descr
  README.md
  doc/compiled-syntax-description.md
  doc/syntax-description.md
Labels: Documentation, Compilation

#116 [Build] Fixed .hie.yaml
  .github/workflows/haskell.yml
  hie.yaml
  libraries/compilation-lib/Exec/Utils.hs
Labels: Build

#125 121 implement instruction datatype
  GLaDOS2023.cabal
  doc/compiled-syntax-description.md
  libraries/compilation-lib/Compilation/Expr.hs
  libraries/compilation-lib/Compilation/Function.hs
  libraries/compilation-lib/Compilation/Utils.hs
  libraries/compilation-lib/Exec.hs
  libraries/compilation-lib/FunctionBlock.hs
  libraries/compilation-lib/Instruction.hs
  libraries/compilation-lib/Parsing.hs
  libraries/compilation-lib/Parsing/Token.hs
  libraries/exec-lib/Exec.hs
  libraries/exec-lib/Exec/Builtins.hs
  libraries/exec-lib/Exec/InteractivePrompt.hs
  libraries/exec-lib/Exec/Registry.hs
  libraries/exec-lib/Exec/RuntimeException.hs
  libraries/exec-lib/Exec/Variables.hs
Labels: Documentation, Compilation

#128 112 implement code interpretation
  GLaDOS2023.cabal
  bin/InteractivePrompt.hs
  libraries/exec-lib/Exec.hs
  libraries/exec-lib/Exec/Builtins.hs
  libraries/exec-lib/Exec/Infer.hs
  libraries/exec-lib/Exec/InferType.hs
  libraries/exec-lib/Exec/Instructions.hs
  libraries/exec-lib/Exec/Registry.hs
  libraries/exec-lib/Exec/RuntimeException.hs
  libraries/exec-lib/Exec/Utils.hs
  libraries/exec-lib/Exec/Variables.hs
  libraries/exec-lib/Parser/ReadFile.hs
  libraries/shared-lib/FunctionBlock.hs
  libraries/shared-lib/Instruction.hs
  libraries/shared-lib/Utils.hs
  runner/Main.hs
  test.cmp
Labels: Execution

#132 [Feature] add conditional and nested conditional
  libraries/exec-lib/Exec.hs
  libraries/exec-lib/Exec/InferType.hs
  libraries/exec-lib/Exec/RuntimeException.hs
  libraries/exec-lib/Parser/ReadFile.hs
  libraries/shared-lib/Instruction.hs
  libraries/shared-lib/Utils.hs
  test.cmp
Labels: Execution

#134 [Test] add unit tests
  GLaDOS2023.cabal
  Makefile
  integration-tests/Test.hs
  libraries/compilation-lib/Compilation/Utils.hs
  libraries/exec-lib/Exec.hs
  libraries/exec-lib/Exec/Builtins.hs
  libraries/exec-lib/Exec/Infer.hs
  libraries/exec-lib/Exec/InferType.hs
  libraries/exec-lib/Exec/RuntimeException.hs
  libraries/exec-lib/Exec/Utils.hs
  libraries/exec-lib/Parser/ReadFile.hs
  libraries/shared-lib/Instruction.hs
  libraries/shared-lib/Utils.hs
  unit-tests/ExecLib.hs
  unit-tests/ExecLib/Exec.hs
  unit-tests/ExecLib/Exec/Infer.hs
  unit-tests/ExecLib/Exec/Instructions.hs
  unit-tests/ExecLib/Exec/Utils.hs
  unit-tests/ExecLib/Parser/ReadFile.hs
  unit-tests/ExecTests.hs
  unit-tests/ParsingTests.hs
  unit-tests/TestMain.hs
Labels: Unit Test, Execution

#135 120 implement compileexpr
  GLaDOS2023.cabal
  compiler/Main.hs
  doc/compiled-syntax-description.md
  libraries/compilation-lib/Compilation/CompilationError.hs
  libraries/compilation-lib/Compilation/Compile.hs
  libraries/compilation-lib/Compilation/Expr.hs
  libraries/compilation-lib/Compilation/Registry.hs
  libraries/compilation-lib/Compilation/RetVal.hs
  libraries/compilation-lib/Parsing/Ast.hs
  libraries/exec-lib/Exec.hs
Labels: Compilation

#139 [Feature] handle arrays
  libraries/exec-lib/Exec/Infer.hs
  libraries/exec-lib/Exec/RuntimeException.hs
  unit-tests/ExecLib/Exec/Infer.hs
Labels: Execution

#144 [Feature] implemented conditionals
  GLaDOS2023.cabal
  compiler/Main.hs
  libraries/compilation-lib/Compilation/Compile.hs
  libraries/compilation-lib/Parsing/Ast.hs
  libraries/compilation-lib/Parsing/Cpt.hs
  libraries/exec-lib/Exec.hs
  libraries/exec-lib/Exec/Builtins.hs
  libraries/exec-lib/Exec/Infer.hs
  libraries/exec-lib/Exec/Instructions.hs
  libraries/exec-lib/Parser/ReadFile.hs
  tests/integration-tests/TestFiles/array_concatenate.scm
  tests/integration-tests/TestFiles/array_concatenate.scm.slv
  tests/integration-tests/TestFiles/array_head.scm
  tests/integration-tests/TestFiles/array_head.scm.slv
  tests/integration-tests/TestFiles/array_init.scm
  tests/integration-tests/TestFiles/array_init.scm.slv
  tests/integration-tests/TestFiles/array_last.scm
  tests/integration-tests/TestFiles/array_last.scm.slv
  tests/integration-tests/TestFiles/array_tail.scm
  tests/integration-tests/TestFiles/array_tail.scm.slv
  tests/integration-tests/TestFiles/factorial.scm
  tests/integration-tests/TestFiles/if3.scm.slv
  tests/integration-tests/TestFiles/superior.scm
  tests/unit-tests/ExecLib/Parser/ReadFile.hs
Labels: Feature, Compilation
