Repository nLatt/GLaDOS-2023, pull requests merged in 2023-02, with the labels that each got.

#28 27 implement script launching
  Makefile
  app/Main.hs
  lib/Parsing/Args.hs
  test/Parsing/ArgsTests.hs
Labels: feature, unit test, Build

#30 24 execution
  GLaDOS2023.cabal
  README.md
  TestFiles/function1.scm
  TestFiles/hello_world.scm
  TestFiles/sample1.scm
  app/Builtins.hs
  app/Main.hs
  execution.md
  lib/Exec.hs
  lib/Exec/Builtins.hs
  lib/Exec/Lookup.hs
  lib/Exec/RuntimeException.hs
  lib/Parsing/Ast.hs
  lib/Parsing/Cpt.hs
  test/ExecTests.hs
  test/Parsing/AstTests.hs
  test/Parsing/CptTests.hs
  test/Parsing/TokenTests.hs
  test/TestMain.hs
Labels: execution

#34 [Refacto] Refacotrs ArgsTests
  lib/Parsing.hs
  test/Parsing/ArgsTests.hs
Labels: unit test

#33 [Feature] implement show instance for Exceptions, messages not final
  lib/Exec/RuntimeException.hs
Labels: enhancement, feature

#36 [Doc] Update Documentation
  README.md
Labels: documentation

#53 [Fix] add patterns matching
  lib/Exec/InteractivePrompt.hs
  lib/Exec/Main.hs
Labels: Bonus, Refacto

#54 24 execution
  GLaDOS2023.cabal
  app/Main.hs
  integrationTests/TestFiles/big_mul.scm
  integrationTests/TestFiles/big_mul.scm.slv
  integrationTests/TestFiles/builtins3.scm
  integrationTests/TestFiles/error.scm.slv
  integrationTests/TestFiles/factorial.scm
  integrationTests/TestFiles/foo.scm
  integrationTests/TestFiles/foo.scm.slv
  integrationTests/TestFiles/function1.scm
  integrationTests/TestFiles/function1.scm.slv
  integrationTests/TestFiles/lambda1.scm
  integrationTests/TestFiles/lambda1.scm.slv
  integrationTests/TestFiles/lambda2.scm
  integrationTests/TestFiles/lambda2.scm.slv
  integrationTests/TestFiles/lambda3.scm
  integrationTests/TestFiles/lambda3.scm.slv
  integrationTests/TestFiles/sample1.scm
  integrationTests/TestFiles/sample1.scm.slv
  lib/Exec.hs
  lib/Exec/Builtins.hs
  lib/Exec/Eval.hs
  lib/Exec/Function.hs
  lib/Exec/InteractivePrompt.hs
  lib/Exec/Main.hs
  lib/Exec/Registry.hs
  lib/Exec/RuntimeException.hs
  lib/Exec/Variables.hs
  lib/Parsing/Ast.hs
  unitTest/ExecTests.hs
Labels: feature, execution

#58 57 add function comments
  app/Main.hs
  lib/Exec/Eval.hs
  lib/Parsing/Args.hs
Labels: bug, documentation, Refacto

#59 56 fix infinite if
  integrationTests/TestFiles/factorial.scm
  lib/Exec/Builtins.hs
  lib/Exec/Eval.hs
Labels: bug

#60 [Fix] Fixed factorial test
  integrationTests/TestFiles/error.scm.slv
  integrationTests/TestFiles/factorial.scm.slv
Labels: unit test

#63 [Doc] Updated README.md
  README.md
Labels: documentation

#65 Develop
  README.md
  app/Main.hs
  lib/Exec/Eval.hs
Labels: documentation

#77 75 implement string handling
  integrationTests/Main.hs
  integrationTests/Test.hs
  integrationTests/TestFiles/complex_infix.scm
  integrationTests/TestFiles/complex_infix.scm.slv
  integrationTests/TestFiles/complex_string.scm
  integrationTests/TestFiles/complex_string.scm.slv
  integrationTests/TestFiles/error.scm
  integrationTests/TestFiles/error.scm.slv
  integrationTests/TestFiles/lambda1.scm
  integrationTests/TestFiles/lambda1.scm.slv
  integrationTests/TestFiles/precedence_infix.scm
  integrationTests/TestFiles/precedence_infix.scm.slv
  integrationTests/TestFiles/simple_string.scm
  integrationTests/TestFiles/simple_string.scm.slv
  lib/Exec.hs
  lib/Exec/Builtins.hs
  lib/Parsing/Ast.hs
  lib/Parsing/Cpt.hs
  lib/Parsing/Token.hs
  unitTest/Parsing/TokenTests.hs
Labels: Feature, Bonus

#73 [Doc] add syntax definition using the ABNF
  README.md
  doc/dev-install.md
  doc/syntax-description.md
Labels: Documentation

#85 [Feature] add infix annotation for custom functions
  README.md
  lib/Exec/Builtins.hs
  lib/Exec/InteractivePrompt.hs
  lib/Parsing/Cpt.hs
  lib/Parsing/Infix.hs
  lib/Parsing/Token.hs
  unitTest/ke
Labels: Feature, Parser

#86 [Fix] fix printing
  lib/Exec/InteractivePrompt.hs
Labels: Bug, Feature
